addons:
 apt:
  packages:
  - valgrind
  - cmake
  - cppcheck
  - cython
language: c
install:
- mkdir -p build
- cd build && cmake .. && make
- cd ..
- python setup.py build_ext
script:
- cd test
- valgrind --error-exitcode=1 --track-origins=yes --leak-check=full ctest
- cd ../..
- cppcheck --error-exitcode=1 -I include/ src
- cd pyx
- python test.py
